:metal:

diff --git a/src/bin/checked-symlink b/src/bin/checked-symlink
--- a/src/bin/checked-symlink
+++ b/src/bin/checked-symlink
@@ -7,31 +7,56 @@ unset IFS
 SOURCE="$1"
 DESTINATION="$2"
 
-if test -e "$DESTINATION"; then
-    RESOLVED_DESTINATION="$(readlink -f "$DESTINATION")"
+# echo "checked-symlink $SOURCE -> $DESTINATION"
 
-    if test "$SOURCE" != "$RESOLVED_DESTINATION"; then
-        RESOLVED_SOURCE="$(readlink -f "$SOURCE")"
-        if test "$RESOLVED_SOURCE" != "$RESOLVED_DESTINATION"; then
-            echo
-            echo >&2 "Error: Destination file '$DESTINATION' already exists."
-            echo >&2 "       Cannot create a symbolic link:"
-            echo >&2 "       '$SOURCE' <- '$DESTINATION'"
-            echo >&2 "       '$SOURCE' != '$DESTINATION"
-            echo >&2 "       '$RESOLVED_SOURCE' != '$RESOLVED_DESTINATION"
-            echo
-        fi
+if test -z "$SOURCE"; then
+    echo >&2 "$(basename "$0"): missing source operand"
+    return
+fi
+
+if test -z "$DESTINATION"; then
+    echo >&2 "$(basename "$0"): missing destination operand after '$SOURCE'"
+    return
+fi
+
+if test ! -e "$SOURCE"; then
+    echo >&2 "$(basename "$0"): cannot stat '$SOURCE': No such file or directory"
+    return
+fi
+
+if test -e "$DESTINATION"; then
+
+    # if test "x$SOURCE" = "x$DESTINATION"; then
+    #     return
+    # fi
+
+    RESOLVED_DESTINATION="$(readlink -f "$DESTINATION")"
+    # if test "x$SOURCE" = "x$RESOLVED_DESTINATION"; then
+    #     return
+    # fi
+
+    RESOLVED_SOURCE="$(readlink -f "$SOURCE")"
+
+    if test "x$RESOLVED_SOURCE" = "x$RESOLVED_DESTINATION"; then
+        return
     fi
 
-elif test ! -e "$SOURCE"; then
-    echo >&2 "Error: Source file or directory '$SOURCE' does not exist. Cannot create a symbolic link."
-elif test -d "$SOURCE"; then
-    ln -sfnv "$SOURCE" "$DESTINATION"
-elif test -f "$SOURCE"; then
-    ln -sfv "$SOURCE" "$DESTINATION"
-else
-    echo
-    echo >&2 "Error: Source '$SOURCE' must be a regular file or directory."
-    echo >&2 "       Cannot create symlink."
-    echo
+    echo >&2 "$(basename "$0"): cannot create symlink $DESTINATION -> $SOURCE"
+    echo >&2 "$(basename "$0"):     Destination already exists!"
+    echo >&2 "$(basename "$0"):     Expect: $RESOLVED_SOURCE"
+    echo >&2 "$(basename "$0"):     Actual: $RESOLVED_DESTINATION"
+
+    return
 fi
+
+if test -d "$SOURCE"; then
+    ln -sfnv "$SOURCE" "$DESTINATION"
+    return
+fi
+
+if test -f "$SOURCE"; then
+    ln -sfv "$SOURCE" "$DESTINATION"
+    return
+fi
+
+echo >&2 "$(basename "$0"): could not create link '$SOURCE' -> '$DESTINATION'"
diff --git a/src/bin/sublime-clean b/src/bin/sublime-clean
--- a/src/bin/sublime-clean
+++ b/src/bin/sublime-clean
@@ -8,32 +8,41 @@ show_usage() {
     cat <<USAGE
 Usage: [PROJECTS_PATH=<PATH>] $(basename "$0") [--exclude-sessions] [--exclude-workspaces]
 
-Cleaning will *only* remove files generated by Sublime Text at runtime like
-caches, indexes, workspaces, sessions, etc. It will not remove installed
-packages, configuration files, etc.
+Removes files generated by Sublime Text.
 
-By default workspaces in the following locations are removed:
+Example: caches, indexes, workspaces, sessions, etc.
 
-1. ./*.sublime-workspace
-2. ./*/*.sublime-workspace
+It does not remove installed packages, configuration files, license, etc.
 
-To specify another location to find workspaces set the PROJECTS_PATH
-environment variable.
+By default, and unless --exclude-workspaces options is set, workspaces in the
+following locations are removed:
 
-Example:
+- ./*.sublime-workspace
+- ./*/*.sublime-workspace
+
+If the PROJECTS_PATH environment variable is set, then workspaces in the
+following locations are also removed:
+
+- ./*.sublime-workspace
+- ./*/*.sublime-workspace
+- ~/projects/*.sublime-workspace
+- ~/projects/*/*.sublime-workspace
+- ~/projects/*/*/*.sublime-workspace
+- ~/projects/.{sublime,st}-projects/*.sublime-workspace
+- ~/projects/.{sublime,st}-workspaces/*.sublime-workspace
+- ~/projects/.{sublime,st}/*.sublime-workspace
+
+Examples:
+
+    $ sublime-clean
+    $ sublime-clean --exclude-sessions
+    $ sublime-clean --exclude-workspaces
+    $ sublime-clean --exclude-sessions --exlude-workspaces
 
     $ PROJECTS_PATH=~/projects sublime-clean
-
-The above will remove workspaces from the following locations:
-
-1. ./*.sublime-workspace
-2. ./*/*.sublime-workspace
-3. ~/projects/*.sublime-workspace
-4. ~/projects/*/*.sublime-workspace
-5. ~/projects/*/*/*.sublime-workspace
-6. ~/projects/.{sublime,st}/*.sublime-workspace
-7. ~/projects/.{sublime,st}-workspaces/*.sublime-workspace
-8. ~/projects/.{sublime,st}-projects/*.sublime-workspace
+    $ PROJECTS_PATH=~/projects sublime-clean --exclude-sessions
+    $ PROJECTS_PATH=~/projects sublime-clean --exclude-workspaces
+    $ PROJECTS_PATH=~/projects sublime-clean --exclude-sessions --exlude-workspaces
 
 USAGE
 }
@@ -53,11 +62,12 @@ while test "$#" != 0; do
 done
 
 if test -n "$(pgrep -f "(subl.*\/plugin_host [0-9]+$|^subl$)")"; then
-  echo >&2 "Please close Sublime Text and run script again"
+  echo >&2 "ERROR: Cannot clean while Sublime Text is running."
+  echo >&2 "ERROR: Please close Sublime Text and run script again."
   exit 1
 fi
 
-echo "cleaning sublime text 2 installation..."
+echo "Clean Sublime Text 2 ..."
 
 # ST2 Linux
 rm -rfv ~/.config/sublime-text-2/Installed\ Packages/
@@ -79,11 +89,11 @@ fi
 rmdir_if_empty() {
     if test -d "$1"; then
         rmdir "$1" || true
-        echo "removed empty directory '$1'"
+        echo "Remove empty directory '$1'"
     fi
 }
 
-echo "cleaning sublime text 3 installation..."
+echo "Clean Sublime Text 3 ..."
 
 # ST3 & ST4
 rm -rfv ~/.cache/sublime-text*/Crash\ Reports/
@@ -138,7 +148,7 @@ rmdir_if_empty ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Col
 rmdir_if_empty ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/SublimeLinter/
 
 if [ "$SUBLIME_CLEAN_INCLUDE_SESSIONS" = "y" ]; then
-    echo "cleaning sublime text sessions..."
+    echo "Clean Sublime Text sessions ..."
     # ST3 Linux sessions
     rm -fv ~/.config/sublime-text-3/Local/*.sublime_session
     # ST4 Linux sessions
@@ -150,7 +160,7 @@ if [ "$SUBLIME_CLEAN_INCLUDE_SESSIONS" = "y" ]; then
 fi
 
 if [ "$SUBLIME_CLEAN_INCLUDE_WORKSPACES" = "y" ]; then
-    echo "cleaning sublime text workspaces..."
+    echo "Clean Sublime Text workspaces ..."
     rm -fv ./*.sublime-workspace
     rm -fv ./*/*.sublime-workspace
     if [ -d "$PROJECTS_PATH" ]; then
@@ -179,4 +189,4 @@ if [ "$SUBLIME_CLEAN_INCLUDE_WORKSPACES" = "y" ]; then
     fi
 fi
 
-echo "Done."
+echo "Done cleaning Sublime Text."
