:zap: :zap: KAPOW

diff --git a/src/bin/extract b/src/bin/extract
--- a/src/bin/extract
+++ b/src/bin/extract
@@ -13,6 +13,7 @@ if test -f "$1"; then
     case $1 in
         *.tar.bz2)  tar -jxvf $1                        ;;
         *.tar.gz)   tar -zxvf $1                        ;;
+        *.tar.xz)   tar -zxvf $1                        ;;
         *.bz2)      bunzip2 $1                          ;;
         *.dmg)      hdiutil mount $1                    ;;
         *.gz)       gunzip $1                           ;;
@@ -25,7 +26,7 @@ if test -f "$1"; then
         *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
         *.rar)      unrar x $1                          ;;
         *.Z)        uncompress $1                       ;;
-        *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
+        *) echo >&2 "$(basename "$0"): cannot be extracted/mounted via extract()"; exit 1 ;;
     esac
 else
     echo >&2 "$(basename "$0"): '$1' is not a valid file"
