:metal:

diff --git a/src/bin/php-cs-fixer b/src/bin/php-cs-fixer
--- a/src/bin/php-cs-fixer
+++ b/src/bin/php-cs-fixer
@@ -1,44 +1,87 @@
 #!/bin/sh
+#
+# https://github.com/FriendsOfPhp/PHP-CS-Fixer
 
 set -e
 unset CDPATH
 unset IFS
 
-is_dev=
+get_local_phpcsfixer_version() {
+    for version_file in .php-cs-fixer-version; do
+        test -f "$version_file" || continue
+        version="$(cat "$version_file" | sed ':a;N;$!ba;s/\n//g')"
+        echo "$version"
+        break
+    done
+}
+
+get_local_phpcsfixer_version_bin() {
+    php_cs_fixer_version="$(get_local_phpcsfixer_version)"
+
+    if test -n "$php_cs_fixer_version"; then
+        php_cs_fixer_bin="/usr/local/bin/php-cs-fixer-$php_cs_fixer_version"
+        if test ! -f "$php_cs_fixer_bin" || test ! -x "$php_cs_fixer_bin"; then
+            echo >&2 "$(basename "$0"): local php-cs-fixer version not found"
+            exit 1
+        fi
+
+        echo "$php_cs_fixer_bin"
+    fi
+}
+
+
+DEV_MODE=
 if test "x$1" = "x--dev"; then
-    is_dev=true
+    DEV_MODE=true
     shift
 fi
 
+# Use local composer installed php-cs-fixer
 if test -f vendor/bin/php-cs-fixer; then
     php_cs_fixer_bin=vendor/bin/php-cs-fixer
+
+# Some projects do this.
 elif test -f laravel/vendor/bin/php-cs-fixer; then
     php_cs_fixer_bin=laravel/vendor/bin/php-cs-fixer
+
+# Default
 else
+
+    # Local default
     php_cs_fixer_bin="$(get_local_phpcsfixer_version_bin)"
+
+    # Global default
     if test -z "$php_cs_fixer_bin"; then
-        php_cs_fixer_bin=php-cs-fixer
+        php_cs_fixer_bin=/usr/local/bin/php-cs-fixer
     fi
 fi
 
-# echo "Using $php_cs_fixer_bin"
-# echo "$("$php_cs_fixer_bin" --version)"
-
-config_file=
-if test -f ./.php_cs.dev && test "x$is_dev" = "xtrue"; then
+# Some projects need a dev override.
+if test -f ./.php_cs.dev && test "x$DEV_MODE" = "xtrue"; then
     config_file=./.php_cs.dev
+
 elif test -f ./.php_cs; then
     config_file=./.php_cs
 elif test -f ./.php_cs.dist; then
     config_file=./.php_cs.dist
+
+# Some projects do this.
 elif test -f ./../.php_cs; then
     config_file=./../.php_cs
+
+# Default to local system configuration.
 elif test -f ~/.php_cs; then
     config_file=~/.php_cs
+
+# Configuration is required.
 else
-    echo "no config found!"
-    return
+    echo >&2 "$(basename "$0"): php-cs-fixer config not found"
+    exit 1
 fi
+
+# echo "Using $php_cs_fixer_bin"
+# echo "Config $config_file"
+# echo "$("$php_cs_fixer_bin" --version)"
 
 if test -n "$config_file"; then
     if test "x$1" = "xfix"; then
